name: "support-service"

services:
    
  support-api:
    build:
      context: ./
      dockerfile: ./api_container/Dockerfile
    ports:
      - "${EXTERNAL_SUPPORT_API_PORT}:${SUPPORT_API_PORT}"
    restart: unless-stopped
    networks:
      - my-services-network

networks:
  my-services-network:
    external: true
